using namespace vex;

using signature = vision::signature;

extern motor mWheelFrontLeft;
extern motor mWheelFrontRight;
extern motor mWheelBackLeft;
extern motor mWheelBackRight;
extern motor mIntakeLeft;
extern motor mIntakeRight;
extern motor mOutputLower;
extern controller Controller1;
extern motor mOutputUpper;
extern optical sOpticalFront;
extern optical sOpticalBack;
extern inertial sInertial;
extern distance sDistanceLeft;
extern distance sDistanceRight;
extern signature sVisionUpper__SIG_BLUE;
extern signature sVisionUpper__SIG_RED;
extern signature sVisionUpper__SIG_GREEN;
extern signature sVisionUpper__SIG_4;
extern signature sVisionUpper__SIG_5;
extern signature sVisionUpper__SIG_6;
extern signature sVisionUpper__SIG_7;
extern vision sVisionUpper;
extern signature sVisionLower__SIG_1;
extern signature sVisionLower__SIG_2;
extern signature sVisionLower__SIG_3;
extern signature sVisionLower__SIG_4;
extern signature sVisionLower__SIG_5;
extern signature sVisionLower__SIG_6;
extern signature sVisionLower__SIG_7;
extern vision sVisionLower;